apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- kured.yaml
images:
- name: docker.io/weaveworks/kured
  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/weaveworks/kured